name: Run Colab Notebook

on:
  schedule:
    - cron: "0 9 * * *"  # runs daily at 9 AM UTC
  workflow_dispatch:  # also allows manual run from GitHub interface

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install papermill jupyter
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Create output directories
        run: |
          mkdir -p temp
          
      - name: Set environment variables
        run: |
          echo "TEMP_DIR=$GITHUB_WORKSPACE/temp" >> $GITHUB_ENV
          echo "MAX_RUNTIME_MINUTES=25" >> $GITHUB_ENV
        
      - name: Run the notebook
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          papermill mynotebook.ipynb output.ipynb -k python3

      - name: Upload output notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: output.ipynb
          
      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-content
          path: temp/
